
package wsClient.candidateWSClient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CandidateWS", targetNamespace = "http://wsServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CandidateWS {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeCandidate", targetNamespace = "http://wsServices/", className = "wsClient.candidateWSClient.RemoveCandidate")
    @ResponseWrapper(localName = "removeCandidateResponse", targetNamespace = "http://wsServices/", className = "wsClient.candidateWSClient.RemoveCandidateResponse")
    public void removeCandidate(
        @WebParam(name = "arg0", targetNamespace = "")
        Candidate arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns wsClient.candidateWSClient.Candidate
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCandidate", targetNamespace = "http://wsServices/", className = "wsClient.candidateWSClient.GetCandidate")
    @ResponseWrapper(localName = "getCandidateResponse", targetNamespace = "http://wsServices/", className = "wsClient.candidateWSClient.GetCandidateResponse")
    public Candidate getCandidate(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<wsClient.candidateWSClient.Candidate>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCandidates", targetNamespace = "http://wsServices/", className = "wsClient.candidateWSClient.GetCandidates")
    @ResponseWrapper(localName = "getCandidatesResponse", targetNamespace = "http://wsServices/", className = "wsClient.candidateWSClient.GetCandidatesResponse")
    public List<Candidate> getCandidates();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateCandidate", targetNamespace = "http://wsServices/", className = "wsClient.candidateWSClient.UpdateCandidate")
    @ResponseWrapper(localName = "updateCandidateResponse", targetNamespace = "http://wsServices/", className = "wsClient.candidateWSClient.UpdateCandidateResponse")
    public void updateCandidate(
        @WebParam(name = "arg0", targetNamespace = "")
        Candidate arg0);

}
