
package wsClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CompanyWSImplService", targetNamespace = "http://wsServices/", wsdlLocation = "http://localhost:8080/lab7_WebServices_war_exploded/CompanyWSImpl?wsdl")
public class CompanyWSImplService
    extends Service
{

    private final static URL COMPANYWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMPANYWSIMPLSERVICE_EXCEPTION;
    private final static QName COMPANYWSIMPLSERVICE_QNAME = new QName("http://wsServices/", "CompanyWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab7_WebServices_war_exploded/CompanyWSImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPANYWSIMPLSERVICE_WSDL_LOCATION = url;
        COMPANYWSIMPLSERVICE_EXCEPTION = e;
    }

    public CompanyWSImplService() {
        super(__getWsdlLocation(), COMPANYWSIMPLSERVICE_QNAME);
    }

    public CompanyWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPANYWSIMPLSERVICE_QNAME, features);
    }

    public CompanyWSImplService(URL wsdlLocation) {
        super(wsdlLocation, COMPANYWSIMPLSERVICE_QNAME);
    }

    public CompanyWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPANYWSIMPLSERVICE_QNAME, features);
    }

    public CompanyWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompanyWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CompanyWS
     */
    @WebEndpoint(name = "CompanyWSImplPort")
    public CompanyWS getCompanyWSImplPort() {
        return super.getPort(new QName("http://wsServices/", "CompanyWSImplPort"), CompanyWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompanyWS
     */
    @WebEndpoint(name = "CompanyWSImplPort")
    public CompanyWS getCompanyWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsServices/", "CompanyWSImplPort"), CompanyWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPANYWSIMPLSERVICE_EXCEPTION!= null) {
            throw COMPANYWSIMPLSERVICE_EXCEPTION;
        }
        return COMPANYWSIMPLSERVICE_WSDL_LOCATION;
    }

}
