
package wsClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DirectorWSImplService", targetNamespace = "http://wsServices/", wsdlLocation = "http://localhost:8080/lab7_WebServices_war_exploded/DirectorWSImpl?wsdl")
public class DirectorWSImplService
    extends Service
{

    private final static URL DIRECTORWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DIRECTORWSIMPLSERVICE_EXCEPTION;
    private final static QName DIRECTORWSIMPLSERVICE_QNAME = new QName("http://wsServices/", "DirectorWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab7_WebServices_war_exploded/DirectorWSImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DIRECTORWSIMPLSERVICE_WSDL_LOCATION = url;
        DIRECTORWSIMPLSERVICE_EXCEPTION = e;
    }

    public DirectorWSImplService() {
        super(__getWsdlLocation(), DIRECTORWSIMPLSERVICE_QNAME);
    }

    public DirectorWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DIRECTORWSIMPLSERVICE_QNAME, features);
    }

    public DirectorWSImplService(URL wsdlLocation) {
        super(wsdlLocation, DIRECTORWSIMPLSERVICE_QNAME);
    }

    public DirectorWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DIRECTORWSIMPLSERVICE_QNAME, features);
    }

    public DirectorWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DirectorWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DirectorWS
     */
    @WebEndpoint(name = "DirectorWSImplPort")
    public DirectorWS getDirectorWSImplPort() {
        return super.getPort(new QName("http://wsServices/", "DirectorWSImplPort"), DirectorWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DirectorWS
     */
    @WebEndpoint(name = "DirectorWSImplPort")
    public DirectorWS getDirectorWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsServices/", "DirectorWSImplPort"), DirectorWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DIRECTORWSIMPLSERVICE_EXCEPTION!= null) {
            throw DIRECTORWSIMPLSERVICE_EXCEPTION;
        }
        return DIRECTORWSIMPLSERVICE_WSDL_LOCATION;
    }

}
