
package wsClient.vacancyWSClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VacancyWSImplService", targetNamespace = "http://wsServices/", wsdlLocation = "http://localhost:8080/lab7_WebServices_war_exploded/VacancyWSImpl?wsdl")
public class VacancyWSImplService
    extends Service
{

    private final static URL VACANCYWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException VACANCYWSIMPLSERVICE_EXCEPTION;
    private final static QName VACANCYWSIMPLSERVICE_QNAME = new QName("http://wsServices/", "VacancyWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab7_WebServices_war_exploded/VacancyWSImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VACANCYWSIMPLSERVICE_WSDL_LOCATION = url;
        VACANCYWSIMPLSERVICE_EXCEPTION = e;
    }

    public VacancyWSImplService() {
        super(__getWsdlLocation(), VACANCYWSIMPLSERVICE_QNAME);
    }

    public VacancyWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VACANCYWSIMPLSERVICE_QNAME, features);
    }

    public VacancyWSImplService(URL wsdlLocation) {
        super(wsdlLocation, VACANCYWSIMPLSERVICE_QNAME);
    }

    public VacancyWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VACANCYWSIMPLSERVICE_QNAME, features);
    }

    public VacancyWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VacancyWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VacancyWS
     */
    @WebEndpoint(name = "VacancyWSImplPort")
    public VacancyWS getVacancyWSImplPort() {
        return super.getPort(new QName("http://wsServices/", "VacancyWSImplPort"), VacancyWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VacancyWS
     */
    @WebEndpoint(name = "VacancyWSImplPort")
    public VacancyWS getVacancyWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsServices/", "VacancyWSImplPort"), VacancyWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VACANCYWSIMPLSERVICE_EXCEPTION!= null) {
            throw VACANCYWSIMPLSERVICE_EXCEPTION;
        }
        return VACANCYWSIMPLSERVICE_WSDL_LOCATION;
    }

}
